### ISSUE TITLE
1.0.3 build error

### ISSUE THREAD

**Issue by aoslee** [bitsensor/elastalert-kibana-plugin#100]
Hi :

Message:
`Attempting to transfer from https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/1.0.3/elastalert-kibana-plugin-1.0.3-6.7.0.zip`
`Transferring 22930892 bytes`
`Transfer complete`
`Retrieving metadata from plugin archive`
`Error: end of central directory record signature not found`
 `   at /usr/share/kibana/node_modules/yauzl/index.js:179:14`
`    at /usr/share/kibana/node_modules/yauzl/index.js:539:5`
`    at /usr/share/kibana/node_modules/fd-slicer/index.js:32:7`
`    at FSReqWrap.wrapper [as oncomplete] (fs.js:463:17)`
`Plugin installation was unsuccessful due to error "Error retrieving metadata from plugin archive"`
`The command '/bin/sh -c /usr/share/kibana/bin/kibana-plugin install https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/1.0.3/elastalert-kibana-plugin-1.0.3-6.7.0.zip' returned a non-zero code: 70`

Dockerfile:
`FROM  docker.elastic.co/kibana/kibana:6.7.0`
`ENV NODE_OPTIONS='--max-old-space-size=4096'`
`RUN /usr/share/kibana/bin/kibana-plugin install  https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/1.0.3/elastalert-kibana-plugin-1.0.3-6.7.0.zip`

Thanks.

**Comment by martijnrondeel** [comment]
When I create a build with the same Dockerfile it installs fine for me:

```
docker build -t test .
Sending build context to Docker daemon  181.4MB
Step 1/3 : FROM docker.elastic.co/kibana/kibana:6.7.0
6.7.0: Pulling from kibana/kibana
8ba884070f61: Pull complete 
3e64ae7e6d2c: Pull complete 
fef1e0e16b16: Pull complete 
27232d48b8e1: Pull complete 
1b7370796631: Pull complete 
2b78de8d43df: Pull complete 
f521c616edb8: Pull complete 
51433302226c: Pull complete 
Digest: sha256:84718c5dfaad5cd8949f2c8129d033730218f7af4f3ffd15acdb2e84b523caab
Status: Downloaded newer image for docker.elastic.co/kibana/kibana:6.7.0
 ---> a19f604cd838
Step 2/3 : ENV NODE_OPTIONS='--max-old-space-size=4096'
 ---> Running in ccfda7796673
Removing intermediate container ccfda7796673
 ---> 5983a2188d9c
Step 3/3 : RUN /usr/share/kibana/bin/kibana-plugin install https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/1.0.3/elastalert-kibana-plugin-1.0.3-6.7.0.zip
 ---> Running in 75e9fdf42a5d
Attempting to transfer from https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/1.0.3/elastalert-kibana-plugin-1.0.3-6.7.0.zip
Transferring 22930892 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation complete
Removing intermediate container 75e9fdf42a5d
 ---> f5b98f7817b1
Successfully built f5b98f7817b1
Successfully tagged test:latest
```

Could you try again, possibly on another device?

**Comment by aoslee** [comment]
Hi @martijnrondeel  :
    You are right.I change another server  ,everything is ok. 
   Thank you very much.
