### ISSUE TITLE
Kibana 6.7.1 support

### ISSUE THREAD

**Issue by Leonorus** [bitsensor/elastalert-kibana-plugin#101]
Please add support for kibana 6.7.1.

Now Installation fails with message:

`Plugin installation was unsuccessful due to error "Plugin elastalert-kibana-plugin [6.7.0] is incompatible with Kibana [6.7.1]"`

**Comment by martijnrondeel** [comment]
Please download the appropriate release.

https://github.com/bitsensor/elastalert-kibana-plugin/releases
