### ISSUE TITLE
Kibana 7.0.0 support

### ISSUE THREAD

**Issue by rockb1017** [bitsensor/elastalert-kibana-plugin#102]
Hello,

Any timeline for when it will be compatible for kibana 7.0.0? 
`Plugin installation was unsuccessful due to error "Plugin elastalert-kibana-plugin [6.7.1] is incompatible with Kibana [7.0.0]"
`
Thank you!

**Comment by Kaminari-Y** [comment]
Hello,

I got the same issue as @rockb1017 , is it related to kibana version?
I got error even I use kibana:6.7.0
```
Plugin installation was unsuccessful due to error "Plugin elastalert-kibana-plugin [6.7.1] is incompatible with Kibana [6.7.0]"
```

Thanks

**Comment by martijnrondeel** [comment]
There is no support yet in ElastAlert for Kibana 7.0 (https://github.com/Yelp/elastalert/pull/2194) so I can't do any testing. Once there is I'll publish a version for Kibana 7.

**Comment by moetemad** [comment]
@martijnrondeel I have installed ElastAlert on Elasticsearch 7.0. I have a dockerized version here: https://github.com/moetemad/elastalert

**Comment by xiangtianyu** [comment]
@martijnrondeel There's a beta release of Elastalert

**Comment by qakart** [comment]
I am also eagerly waiting for 7.0.0 release

**Comment by martijnrondeel** [comment]
There is a release now with support for Kibana 7.0.0 and higher.

https://github.com/bitsensor/elastalert-kibana-plugin/releases/tag/1.0.4

**Comment by rajatppn** [comment]
This doesn't work with kibana 7.0.1 
Plugin installation was unsuccessful due to error "Plugin elastalert-kibana-plugin [7.0.0] is incompatible with Kibana [7.0.1]"

**Comment by martijnrondeel** [comment]
@rajatppn Please look at the listed assets in the release and get the **7.0.1** release.

**Comment by rajatppn** [comment]
> This doesn't work with kibana 7.0.1
> Plugin installation was unsuccessful due to error "Plugin elastalert-kibana-plugin [7.0.0] is incompatible with Kibana [7.0.1]"

Raised a new issue at https://github.com/bitsensor/elastalert-kibana-plugin/issues/105

**Comment by rajatppn** [comment]
@martijnrondeel Sorry, that was bad oversight on my part. Thank you so much for the quick response!

**Comment by moetemad** [comment]
I am having problems making this work on kibana 7.0. Here is the error:

> {"type":"log","@timestamp":"2019-05-14T13:55:52Z","tags":["info","optimize"],"pid":1,"message":"Optimizing and caching bundles for graph, monitoring, space_selector, login, logout, logged_out, ml, dashboardViewer, apm, maps, canvas, infra, uptime, elastalert-kibana-plugin, kibana, stateSessionStorageRedirect, status_page and timelion. This may take a few minutes"}
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at Pipe.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by moetemad** [comment]
Having problems making this work on kibana 7.0. Here is the error:

{"type":"log","@timestamp":"2019-05-14T13:55:52Z","tags":["info","optimize"],"pid":1,"message":"Optimizing and caching bundles for graph, monitoring, space_selector, login, logout, logged_out, ml, dashboardViewer, apm, maps, canvas, infra, uptime, elastalert-kibana-plugin, kibana, stateSessionStorageRedirect, status_page and timelion. This may take a few minutes"} events.js:174 throw er; // Unhandled 'error' event ^ Error: read ECONNRESET at Pipe.onStreamRead (internal/stream_base_commons.js:111:27) Emitted 'error' event at: at emitErrorNT (internal/streams/destroy.js:82:8) at emitErrorAndCloseNT (internal/streams/destroy.js:50:3) at process._tickCallback (internal/process/next_tick.js:63:19)
