### ISSUE TITLE
Kibana 7.0.1 support

### ISSUE THREAD

**Issue by rajatppn** [bitsensor/elastalert-kibana-plugin#105]
Hey!
Unable to run the plugin with Kibana 7.0.1 even after the latest elastalert 7.0.0 update.
Obtained the following error
`Plugin installation was unsuccessful due to error "Plugin elastalert-kibana-plugin [7.0.0] is incompatible with Kibana [7.0.1]"`

**Comment by martijnrondeel** [comment]
https://github.com/bitsensor/elastalert-kibana-plugin/issues/102#issuecomment-492187085
