### ISSUE TITLE
Kibana 7.0 support

### ISSUE THREAD

**Issue by moetemad** [bitsensor/elastalert-kibana-plugin#107]
Having problems making this work on kibana 7.0. Here is the error:

`{"type":"log","@timestamp":"2019-05-14T13:55:52Z","tags":["info","optimize"],"pid":1,"message":"Optimizing and caching bundles for graph, monitoring, space_selector, login, logout, logged_out, ml, dashboardViewer, apm, maps, canvas, infra, uptime, elastalert-kibana-plugin, kibana, stateSessionStorageRedirect, status_page and timelion. This may take a few minutes"} events.js:174 throw er; // Unhandled 'error' event ^ Error: read ECONNRESET at Pipe.onStreamRead (internal/stream_base_commons.js:111:27) Emitted 'error' event at: at emitErrorNT (internal/streams/destroy.js:82:8) at emitErrorAndCloseNT (internal/streams/destroy.js:50:3) at process._tickCallback (internal/process/next_tick.js:63:19)`

**Comment by moetemad** [comment]
I get this error on both 7.0.0 and 7.0.1 versions of kibana when installing elastalert (the respective version).

**Comment by martijnrondeel** [comment]
I'm not getting this problem on installation:

```
{"type":"log","@timestamp":"2019-05-16T08:06:55Z","tags":["info","optimize"],"pid":1,"message":"Optimizing and caching bundles for graph, monitoring, space_selector, login, logout, logged_out, ml, dashboardViewer, apm, maps, canvas, infra, uptime, bitsensor, elastalert-kibana-plugin, kibana, stateSessionStorageRedirect, status_page and timelion. This may take a few minutes"}
{"type":"log","@timestamp":"2019-05-16T08:07:47Z","tags":["info","optimize"],"pid":1,"message":"Optimization of bundles for graph, monitoring, space_selector, login, logout, logged_out, ml, dashboardViewer, apm, maps, canvas, infra, uptime, bitsensor, elastalert-kibana-plugin, kibana, stateSessionStorageRedirect, status_page and timelion complete in 52.43 seconds"}
```

Please share some details about your environment.

**Comment by moetemad** [comment]
@martijnrondeel 
So I do get that first line in the logs but then the error appears:

> {"type":"log","@timestamp":"2019-05-16T13:02:43Z","tags":["info","optimize"],"pid":1,"message":"Optimizing and caching bundles for graph, monitoring, space_selector, login, logout, logged_out, ml, dashboardViewer, apm, maps, canvas, infra, uptime, elastalert-kibana-plugin, kibana, stateSessionStorageRedirect, status_page and timelion. This may take a few minutes"}
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.afterWrite (net.js:782:14)
Emitted 'error' event at:
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at Socket._destroy (net.js:607:3)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite (net.js:784:10)

I am using this in a Docker environment. Here is my Dockerfile:

 `FROM docker.elastic.co/kibana/kibana:7.0.1
RUN ./bin/kibana-plugin install https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/1.0.4/elastalert-kibana-plugin-1.0.4-7.0.1.zip
RUN rm -rf config/kibana.yml
RUN touch config/kibana.yml
RUN echo "---" >> config/kibana.yml
RUN echo "server.name: kibana" >> config/kibana.yml
RUN echo "server.host: \"0\"" >> config/kibana.yml
CMD ["bin/kibana"]
`
I also tried adding 
`RUN echo "elastalert-kibana-plugin.serverHost: 192.168.59.237" >> config/kibana.yml`
But no difference.

**Comment by moetemad** [comment]
Here is what I used to make it work FYI:

`FROM alpine:latest as py-ea
ARG ELASTALERT_VERSION=v0.1.39
ENV ELASTALERT_VERSION=${ELASTALERT_VERSION}
# URL from which to download Elastalert.
ARG ELASTALERT_URL=https://github.com/matsgoran/elastalert/archive/doc_type_and_support_for_es66_es7.zip
ENV ELASTALERT_URL=${ELASTALERT_URL}
# Elastalert home directory full path.
ENV ELASTALERT_HOME /opt/elastalert

WORKDIR /opt

RUN apk add --update --no-cache ca-certificates openssl-dev openssl python2-dev python2 py2-pip py2-yaml libffi-dev gcc musl-dev wget && \
# Download and unpack Elastalert.
    wget -O elastalert.zip "${ELASTALERT_URL}" && \
    unzip elastalert.zip && \
    rm elastalert.zip && \
    mv e* "${ELASTALERT_HOME}"

WORKDIR "${ELASTALERT_HOME}"

# Install Elastalert.
# see: https://github.com/Yelp/elastalert/issues/1654
#RUN sed -i 's/jira>=1.0.10/jira>=1.0.10,<1.0.15/g' setup.py && \
#RUN sed -i 's/0.1.38/0.2.0b2/g' setup.py && \
#    python setup.py install && \
#    pip install -r requirements.txt

RUN pip install "elastalert>=0.2.0b"

FROM node:alpine
LABEL maintainer="BitSensor <dev@bitsensor.io>"
# Set timezone for this container
ENV TZ Etc/UTC

RUN apk add --update --no-cache curl tzdata python2 make libmagic

COPY --from=py-ea /usr/lib/python2.7/site-packages /usr/lib/python2.7/site-packages
COPY --from=py-ea /opt/elastalert /opt/elastalert
COPY --from=py-ea /usr/bin/elastalert* /usr/bin/

WORKDIR /opt/elastalert-server
COPY . /opt/elastalert-server

RUN npm install --production --quiet
COPY config/elastalert.yaml /opt/elastalert/config.yaml
COPY config/elastalert-test.yaml /opt/elastalert/config-test.yaml
COPY config/config.json config/config.json
#COPY elastalert_modules/ /opt/elastalert/elastalert_modules

EXPOSE 3030
ENTRYPOINT ["npm", "start"]
`

**Comment by nerddelphi** [comment]
I'm getting the same issue? What I have to do?
