### ISSUE TITLE
Kibana Plugin License

### ISSUE THREAD

**Issue by jochenkressin** [bitsensor/elastalert-kibana-plugin#11]
Hi,

I cannot find any license information regarding the ElastAlert Kibana Plugin in the repository. Under what license is it published?

Thanks,

Jochen

**Comment by CodingSpiderFox** [comment]
The back-end part is under BSD license: https://git.bitsensor.io/back-end/elastalert 

@RubieV: does the same license apply to the front-end? Can you please add a license to this and the original repo at bitsensor? 

Thanks in advance :)

**Comment by CodingSpiderFox** [comment]
Thanks a lot!
