### ISSUE TITLE
Kibana 7.1 support

### ISSUE THREAD

**Issue by arber-od** [bitsensor/elastalert-kibana-plugin#110]
Please make support for Kibana 7.1.0

https://www.elastic.co/downloads/elasticsearch

**Comment by branchnetconsulting** [comment]
Is there any chance that changing there "version" value in
kibana/elastalert-kibana-plugin/package.json
in the 7.0.1 plugin package file from "7.0.1" to "7.1.1" would be enough to make the plugin compatible with Kibana 7.1.1?  It appears that is the only difference between the 7.0.0 and 7.0.1 plugin packages.  It does not look like that much has changed from Kibana 7.0 to 7.1 other than making basic RBAC a free feature.

**Comment by derentis** [comment]
> Is there any chance that simply changing the "version" value in
> kibana/elastalert-kibana-plugin/package.json
> in the 7.0.1 plugin package file from "7.0.1" to "7.1.1" would be enough to make the plugin compatible with Kibana 7.1.1? It appears that is the only difference between the 7.0.0 and 7.0.1 plugin packages. It does not look like that much has changed from Kibana 7.0 to 7.1 other than making basic RBAC a free feature.

Gave it try, seems to work

**Comment by branchnetconsulting** [comment]
Thanks.  We'll be making our first attempt ever at deploying the ElastAlert Kibana app shortly.  I plan to report back here if we run into the same issue you reported.

**Comment by robincher** [comment]
@branchnetconsulting lets us know :) i be the second!

**Comment by martijnrondeel** [comment]
I added a 7.1.0 and 7.1.1 version for release 1.0.4.

**Comment by webhead404** [comment]
@martijnrondeel the plugin does not seem to be displaying in Kibana 7.1.0. The Elastalert server is working as expected.
