### ISSUE TITLE
Kibana 6.8 support

### ISSUE THREAD

**Issue by birish2** [bitsensor/elastalert-kibana-plugin#111]
Please add support for Kibana 6.8.0

**Comment by surfer190** [comment]
@birish2 @martijnrondeel From what I can see in this commit https://github.com/bitsensor/elastalert-kibana-plugin/commit/4ed371306b8b589b7db6b810c7a4872f4e721868, it is just a case of bumping versions and running tests.

It is annoying that everytime kibana updates plugins have to be changed...

**Comment by martijnrondeel** [comment]
There's a 6.8.0 version now in release 1.0.3!

**Comment by buptsmartcar** [comment]
how can i use this plugin for kibana 6.8.2?
