### ISSUE TITLE
Support for Kibana 7.5.1, 7.5.2, 7.6.0 and 7.6.1

### ISSUE THREAD

**Issue by AhmadMS1988** [bitsensor/elastalert-kibana-plugin#147]
Hi;
Is their a plan to support the newer Kibana version "7.5.1, 7.5.2, 7.6.0 and 7.6.1" and release in a newer version of the plugin or at lease have the current version build for these kibana version?
Thank you very much

**Comment by chuyengiason** [comment]
just unzip the zip file and edit file : package.json, change kibana.version to your version and the plugin should work

**Comment by AhmadMS1988** [comment]
Is it safe to do so with 7.6.0 and 7.6.1? Is not there any dependency conflict?

**Comment by nsano-rururu** [comment]
@AhmadMS1988 

The combination of Kibana 7.6.0 and elastalert-kibana-plugin has been registered as a bug in the Kibana issue. Until fixed, elastalert-kibana-plugin will not work with Kibana 7.6.0 (and probably also Kibana 7.6.1).

[Plugin is incompatible with Kibana 7.6.0 #141](https://github.com/bitsensor/elastalert-kibana-plugin/issues/141)
[[Legacy] Route payload must be set to 'parse' when payload validation enabled #57777](https://github.com/elastic/kibana/issues/57777)

How to create an elastalert-kibana-plugin zip file for Kibana 7.5.1

```
cd /tmp
curl -L -O https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/1.1.0/elastalert-kibana-plugin-1.1.0-7.5.0.zip
mv elastalert-kibana-plugin-1.1.0-7.5.0.zip elastalert-kibana-plugin-1.1.0-7.5.1.zip
unzip elastalert-kibana-plugin-1.1.0-7.5.1.zip kibana/elastalert-kibana-plugin/package.json
sed -i "s/7\.5\.0/7\.5\.1/g" kibana/elastalert-kibana-plugin/package.json
zip elastalert-kibana-plugin-1.1.0-7.5.1.zip kibana/elastalert-kibana-plugin/package.json
rm -rf kibana
```

How to create an elastalert-kibana-plugin zip file for Kibana 7.5.2

```
cd /tmp
curl -L -O https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/1.1.0/elastalert-kibana-plugin-1.1.0-7.5.0.zip
mv elastalert-kibana-plugin-1.1.0-7.5.0.zip elastalert-kibana-plugin-1.1.0-7.5.2.zip
unzip elastalert-kibana-plugin-1.1.0-7.5.2.zip kibana/elastalert-kibana-plugin/package.json
sed -i "s/7\.5\.0/7\.5\.2/g" kibana/elastalert-kibana-plugin/package.json
zip elastalert-kibana-plugin-1.1.0-7.5.2.zip kibana/elastalert-kibana-plugin/package.json
rm -rf kibana
```

**Comment by nsano-rururu** [comment]
@AhmadMS1988 

How to create an elastalert-kibana-plugin zip file for Kibana 7.6.0

```
cd /tmp
curl -L -O https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/1.1.0/elastalert-kibana-plugin-1.1.0-7.5.0.zip
# [update elasticsearch to 7.6.2; also, fix issue idaholab#119](https://github.com/mmguero-dev/Malcolm/commit/b38ddb7f0d4c5b03e6f8ccad58a656644e113b19)
curl -L -O https://raw.githubusercontent.com/mmguero-dev/Malcolm/development/kibana/elastalert-kibana-plugin/server/routes/elastalert.js
mv elastalert.js elastalert-server-routes.js
mv elastalert-kibana-plugin-1.1.0-7.5.0.zip elastalert-kibana-plugin-1.1.0-7.6.0.zip
unzip elastalert-kibana-plugin-1.1.0-7.6.0.zip kibana/elastalert-kibana-plugin/package.json
sed -i "s/7\.5\.0/7\.6\.0/g" kibana/elastalert-kibana-plugin/package.json
mkdir -p kibana/elastalert-kibana-plugin/server/routes/
cp /tmp/elastalert-server-routes.js kibana/elastalert-kibana-plugin/server/routes/elastalert.js
zip elastalert-kibana-plugin-1.1.0-7.6.0.zip kibana/elastalert-kibana-plugin/package.json kibana/elastalert-kibana-plugin/server/routes/elastalert.js
rm -rf kibana
rm elastalert-server-routes.js
```

How to create an elastalert-kibana-plugin zip file for Kibana 7.6.1

```
cd /tmp
curl -L -O https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/1.1.0/elastalert-kibana-plugin-1.1.0-7.5.0.zip
# [update elasticsearch to 7.6.2; also, fix issue idaholab#119](https://github.com/mmguero-dev/Malcolm/commit/b38ddb7f0d4c5b03e6f8ccad58a656644e113b19)
curl -L -O https://raw.githubusercontent.com/mmguero-dev/Malcolm/development/kibana/elastalert-kibana-plugin/server/routes/elastalert.js
mv elastalert.js elastalert-server-routes.js
mv elastalert-kibana-plugin-1.1.0-7.5.0.zip elastalert-kibana-plugin-1.1.0-7.6.1.zip
unzip elastalert-kibana-plugin-1.1.0-7.6.1.zip kibana/elastalert-kibana-plugin/package.json
sed -i "s/7\.5\.0/7\.6\.1/g" kibana/elastalert-kibana-plugin/package.json
mkdir -p kibana/elastalert-kibana-plugin/server/routes/
cp /tmp/elastalert-server-routes.js kibana/elastalert-kibana-plugin/server/routes/elastalert.js
zip elastalert-kibana-plugin-1.1.0-7.6.1.zip kibana/elastalert-kibana-plugin/package.json kibana/elastalert-kibana-plugin/server/routes/elastalert.js
rm -rf kibana
rm elastalert-server-routes.js
```

How to create an elastalert-kibana-plugin zip file for Kibana 7.6.2

```
cd /tmp
curl -L -O https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/1.1.0/elastalert-kibana-plugin-1.1.0-7.5.0.zip
# [update elasticsearch to 7.6.2; also, fix issue idaholab#119](https://github.com/mmguero-dev/Malcolm/commit/b38ddb7f0d4c5b03e6f8ccad58a656644e113b19)
curl -L -O https://raw.githubusercontent.com/mmguero-dev/Malcolm/development/kibana/elastalert-kibana-plugin/server/routes/elastalert.js
mv elastalert.js elastalert-server-routes.js
mv elastalert-kibana-plugin-1.1.0-7.5.0.zip elastalert-kibana-plugin-1.1.0-7.6.2.zip
unzip elastalert-kibana-plugin-1.1.0-7.6.2.zip kibana/elastalert-kibana-plugin/package.json
sed -i "s/7\.5\.0/7\.6\.2/g" kibana/elastalert-kibana-plugin/package.json
mkdir -p kibana/elastalert-kibana-plugin/server/routes/
cp /tmp/elastalert-server-routes.js kibana/elastalert-kibana-plugin/server/routes/elastalert.js
zip elastalert-kibana-plugin-1.1.0-7.6.2.zip kibana/elastalert-kibana-plugin/package.json kibana/elastalert-kibana-plugin/server/routes/elastalert.js
rm -rf kibana
rm elastalert-server-routes.js
```

**Comment by vas-rus** [comment]
@AhmadMS1988 @nsano-rururu is this fix working for 7.6 version ? 
I got Plugin is incompatible with Kibana 7.6.0 error without changing

**Comment by whataboutpereira** [comment]
This specific script is for 7.6.2. You need to replace 7.5.0 with 7.6.0 if you're using 7.6.0.

**Comment by nsano-rururu** [comment]
> This specific script is for 7.6.2. You need to replace 7.5.0 with 7.6.0 if you're using 7.6.0.

wrong. This is a script to support 7.6.0 or later. See the following site for details. 

https://github.com/elastic/kibana/issues/57777#issuecomment-608516900

The person who created the script has issued a pull request. If you don't need to use it now with Kibana 7.6.0 or later, please wait for the fix to be incorporated

**Comment by whataboutpereira** [comment]
> 
> 
> > This specific script is for 7.6.2. You need to replace 7.5.0 with 7.6.0 if you're using 7.6.0.
> 
> wrong. This is a script to support 7.6.0 or later. See the following site for details.

Indeed. I scrolled up and saw "How to create an elastalert-kibana-plugin zip file for Kibana 7.6.2". :) Didn't scroll high enough. Provided @vas-rus used the 7.6.0 section to prepare the zip file.

**Comment by AhmadMS1988** [comment]
It is working in 7.6.2.
Thanks all

**Comment by vas-rus** [comment]
@AhmadMS1988 @whataboutpereira @nsano-rururu  
got this below error for 7.6.2 after making local zip   

```
bash-4.2$ /usr/share/kibana/bin/kibana-plugin install elastalert-kibana-plugin-1.1.0-7.6.2.zip
Attempting to transfer from elastalert-kibana-plugin-1.1.0-7.6.2.zip
Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/elastalert-kibana-plugin-1.1.0-7.6.2.zip/elastalert-kibana-plugin-1.1.0-7.6.2.zip-7.6.2.zip
Plugin installation was unsuccessful due to error "No valid url specified."
```

**Comment by AhmadMS1988** [comment]
@vas-rus 
Because you have gave a package name without a URL, kibana tried to download it from elastic plugins repository.
Instead u may use:
/usr/share/kibana/bin/kibana-plugin install file:///path/to/elastalert-kibana-plugin-1.1.0-7.6.2.zip

Reference: 
1. https://www.elastic.co/guide/en/kibana/current/install-plugin.html
1. https://www.elastic.co/guide/en/elasticsearch/plugins/current/plugin-management-custom-url.html

**Comment by vas-rus** [comment]
Got it thanks

**Comment by vas-rus** [comment]
in 7.6.2 I am still getting this error :

`FATAL  AssertionError [ERR_ASSERTION]: Route payload must be set to 'parse' when payload validation enabled: POST /api/elastalert/{path*}
`

Copied above exact commands and elastalert.js to install plugin
@AhmadMS1988 Can you please help again ?
