### ISSUE TITLE
Will this plugin work with OpenDistro Elasticsearch

### ISSUE THREAD

**Issue by rpotnuru** [bitsensor/elastalert-kibana-plugin#157]
Hello, 

We use Open Distro for Elasticsearch, does this plugin work with OpenDistro Elasticsearch ? Appreciate your quick help.

Thanks, Ravi.

**Comment by nsano-rururu** [comment]
It is possible to check the operation if you can provide a way to work with docker-compose of Open Distro for Elasticsearch.

The development of the ElastAlert Kibana Plugin is probably over. I don't think there will be a new version.

**Comment by nsano-rururu** [comment]
Please close the issue if you do not intend to provide any information

**Comment by rpotnuru** [comment]
thank  you @nsano-rururu for the update.
