### ISSUE TITLE
Kibana 7.10 support

### ISSUE THREAD

**Issue by Makss39** [bitsensor/elastalert-kibana-plugin#165]
Hello,

Is there a way to make it works on Kibana 7.10 ?
I tried to modify the package.json of 7.5 to change version by 7.10 but i get the following error :

`Plugin installation was unsuccessful due to error "No kibana plugins found in archive"`

Thanks !

**Comment by nsano-rururu** [comment]
As Kibana 7.10.0 is removing the functions used by the legacy plugins, we have to start migrating elastalert-kibana-plugin to a new platform.

This link shows the requirements and the process to do this migration:
Migrating legacy plugins to the new platform
https://github.com/elastic/kibana/blob/v7.10.0/src/core/MIGRATION.md
https://github.com/elastic/kibana/blob/v7.10.0/src/core/MIGRATION_EXAMPLES.md
https://www.elastic.co/guide/en/kibana/7.10/migrating-legacy-plugins-examples.html
https://www.elastic.co/guide/en/kibana/current/migrating-legacy-plugins.html
https://github.com/elastic/kibana/tree/master/packages/kbn-config-schema

**Comment by nsano-rururu** [comment]
Good luck

**Comment by nsano-rururu** [comment]
This project is dead, so I don't think there will be any features or bug fixes.

**Comment by Makss39** [comment]
Okey thanks for the hint ! 
So no alternative to have a GUI alerts managment instead of X-pack ?

**Comment by nsano-rururu** [comment]
Praeco
https://github.com/johnsusek/praeco

**Comment by nsano-rururu** [comment]
I'm the maintainer of Praeco

**Comment by Makss39** [comment]
Great, i'll have a look so :)
Many thanks !

I close

**Comment by nsano-rururu** [comment]
**Watcher**

https://www.elastic.co/guide/en/kibana/7.10/watcher-ui.html

**Alerting and action settings in Kibana**

[Alerts and Actions](https://www.elastic.co/guide/en/kibana/current/managing-alerts-and-actions.html)
[Managing Alerts](https://www.elastic.co/guide/en/kibana/current/alert-management.html)
[Alert details](https://www.elastic.co/guide/en/kibana/current/alert-details.html)
[Managing Connectors](https://www.elastic.co/guide/en/kibana/current/connector-management.html)

**Open Distro for Elasticsearch**

[Alerting](https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/)

**Grafana**

Perform alerting on data in Elasticsearch with Grafana
https://grafana.com/docs/grafana/latest/alerting/
https://grafana.com/docs/grafana/latest/alerting/notifications/

**Comment by Makss39** [comment]
Thanks, but emails alerts are only available with minimum a Gold licence....
And I already have all installed on the Basic ELK stack... I'll dig in Praeco !
