### ISSUE TITLE
Elastalert-Kibana Plugin Error [Kibana 7.10.2]: "undefined - undefined. Cannot read property 'sort' of undefined"

### ISSUE THREAD

**Issue by boomallari** [bitsensor/elastalert-kibana-plugin#167]
![elastalert-kibana plugin error](https://user-images.githubusercontent.com/83259247/116176940-8de35500-a745-11eb-8b98-57248deb38bc.PNG)

Has anyone experienced this issue? Please advise on what could be the cause.
This is the first time I installed the plugin.

My current setup is:
- Elastalert-Kibana plugin version 1.4.0
- Kibana version 7.10.2
- Added the configuration to kibana.yml:
elastalertKibanaPlugin.serverHost: ("my ES IP")
elastalertKibanaPlugin.serverPort: 9200
- Elastalert is direct installation

Thank you

**Comment by nsano-rururu** [comment]
look
https://github.com/bitsensor/elastalert-kibana-plugin/issues/166

**Comment by nsano-rururu** [comment]
@boomallari 

It doesn't make sense if you don't post to the following developer issues
https://github.com/Karql/elastalert/issues

**Comment by boomallari** [comment]
@nsano-rururu let me post there instead. Thanks
