### ISSUE TITLE
kibana5 install zip paths not working - 404 error

### ISSUE THREAD

**Issue by nsvijay04b1** [bitsensor/elastalert-kibana-plugin#24]
All of the links for kibana 5 elastalert plugin in your github page, bitsensor blogs are not working, old/wrong .

https://git.bitsensor.io/front-end/elastalert-kibana-plugin/builds/5251/artifacts/file/build/elastalert-0.0.6.zip

https://git.bitsensor.io/front-end/elastalert-kibana-plugin/builds/artifacts/kibana5/raw/artifact/elastalert--latest.zip?job=build

please update below sites with correct kibana 5 links

https://bitsensor.io/blog/community-update-alerting-in-kibana

https://hub.docker.com/r/bitsensor/elastalert/

https://github.com/bitsensor/elastalert-kibana-plugin

**Comment by pratik1992** [comment]
Yes the url seems to be invalid and a 404 on same . Kindly update the url paths for kibana 5.x.x

**Comment by RubieV** [comment]
Than you for your great find @nsvijay04b1 and @martinwalsh for your writeup. I have updated documentation in the blog at https://bitsensor.io/blog/community-update-alerting-in-kibana. Also, the  README.MD on the master branch with commit https://github.com/bitsensor/elastalert-kibana-plugin/commit/2f75406065e7d93a2b4c245faec1e6be3a4cd67a is now updated to include the clarification.

Do you feel comfortable that there is enough explanation now? If not, feel free to reopen and do a PR.
