### ISSUE TITLE
Unable to add enhancement 

### ISSUE THREAD

**Issue by FriedCircuits** [bitsensor/elastalert-kibana-plugin#28]
Hi, 

I trying to load my own enhancement but I noticed that the docker directions doesn't mount the elastalert_modules directory. So should I be adding that to the mount points or is there another way to load your own modules?

Thanks.

**Comment by RubieV** [comment]
Adding it as mount point makes sense indeed. Could you open a PR?

**Comment by FriedCircuits** [comment]
Added PR #29

**Comment by RubieV** [comment]
Closed with https://github.com/bitsensor/elastalert-kibana-plugin/pull/29
