### ISSUE TITLE
External use of elastalert.

### ISSUE THREAD

**Issue by runtman** [bitsensor/elastalert-kibana-plugin#31]
This is more of a question rather than an issue but I can't seem to find where I can ask that?

Does this work with the standard elastalert version or does this plugin have to specifically use the version with your repositories? We use elastalert on it's on box as well as the elasticsearch stack however the docker container provider seems to expect both elastalert and elasticsearch to be local.

Ideally I would want to use elastalert running on a different server using the standard version supplied by Yelp. 

Can you confirm if this is possible, or if your version of Elastalert provides differences?

**Comment by RubieV** [comment]
Absolutely, just adjust the `config/elastalert.yaml` to use a different host.

```bash
docker run -d -p 3030:3030 \
    -v `pwd`/config/elastalert.yaml:/opt/elastalert/config.yaml \
    -v `pwd`/config/config.json:/opt/elastalert-server/config/config.json \
    -v `pwd`/rules:/opt/elastalert/rules \
    -v `pwd`/rule_templates:/opt/elastalert/rule_templates \
    --net="host" \
    --name elastalert bitsensor/elastalert:latest
```

**Comment by runtman** [comment]
Ok, that is fine and I have that working. However although I set a hostname via `-h blah`
When the container talks to ES it still presents it's internal IP?

`[2017-12-04T12:17:45,344][TRACE][c.f.s.s.t.SearchGuardSSLNettyTransport] [elastic-master-01.x] channel closed: [id: 0x5577a8ec, L:/172.31.33.13:9300 ! R:/172.31.35.12:38650]`

```
docker inspect efbf22103eb0 | grep Host
        "HostnamePath": "/var/lib/docker/containers/efbf22103eb06430864e61d72c1166164cc256de8ea9d94f6683875c4c99f034/hostname",
        "HostsPath": "/var/lib/docker/containers/efbf22103eb06430864e61d72c1166164cc256de8ea9d94f6683875c4c99f034/hosts",
        "HostConfig": {
                        "HostIp": "",
                        "HostPort": "3030"
            "ExtraHosts": null,
            "Hostname": "elastalert-1.x",
```

Which causes SSL certificate errors, any idea how I would get around that?

Also curious of the kibana plugin can talk to this if it's on another host, what do I need to do, or is the only option an NFS share?

**Comment by RubieV** [comment]
You should be able to set a hostname, which will then be resolved. The Kibana plugin is also capable of talking to a different host, see the readme:

Append to the `config/kibana.yml` file the host of ElastAlert server, if it is different than localhost. Typically the case if you are running on macOS.
```yml
elastalert.serverHost: yourElasatAlertHost
```

**Comment by runtman** [comment]
I am setting the hostname on the container, but it's not being passed to elasticsearch as my log above. I am using the following:

```
docker run -d -p 3030:3030 \
    -v `pwd`/config/elastalert.yaml:/opt/elastalert/config.yaml \
    -v `pwd`/config/config.json:/opt/elastalert-server/config/config.json \
    -v `pwd`/rules:/opt/elastalert/rules \
    -v `pwd`/rule_templates:/opt/elastalert/rule_templates \
    -v `pwd`/elastalert_modules:/opt/elastalert/elastalert_modules \
    -v `pwd`/ssl/elastic-admin-key.pem:/opt/elastalert/elastic-admin-key.pem \
    -v `pwd`/ssl/ca-bundle.pem:/opt/elastalert/ca-bundle.pem \
    -v `pwd`/ssl/elastic-admin.pem:/opt/elastalert/elastic-admin.pem \
    --net="host" \
    -h elastalert-1.x \
    --name elastalert bitsensor/elastalert:latest
```
Or does it need to be set in a config somewhere?

**Comment by runtman** [comment]
I think this is more of a docker problem to be honest, can you confirm if bitsensor(Kibana plugin) will work with a normal installation of Elastalert or do I need your specific version?

**Comment by RubieV** [comment]
You can install it without Docker, please read the Dockerfile of github.com/bitsensor/elastalert on how to do a local install.
