### ISSUE TITLE
Kibana Version 5.6.5 support?

### ISSUE THREAD

**Issue by jreker** [bitsensor/elastalert-kibana-plugin#33]
Hello,

this is such a great plugin/project. I want to use it with our kibana version 5.6.5. How can i install it? I is not working with the following command:

> ./bin/kibana-plugin install https://git.bitsensor.io/front-end/elastalert-kibana-plugin/-/jobs/9877/artifacts/raw/artifact/elastalert-5.6.5-latest.zip?job=build

Is there a version? Or what can i do? 
Thanks in advance!

**Comment by RubieV** [comment]
`./bin/kibana-plugin install https://git.bitsensor.io/front-end/elastalert-kibana-plugin/builds/artifacts/kibana5/raw/artifact/elastalert-5.x.x-latest.zip?job=build` should work. If not, please provide the Kibana stdout logs.

**Comment by jreker** [comment]
Thanks for your fast answer.
I get the following error message: 
`Plugin installation was unsuccessful due to error "No valid url specified."
`

**Comment by RubieV** [comment]
Closed with 629a200, added support for kibana 5.6.5.

**Comment by jreker** [comment]
It is still not working..?!

**Comment by RubieV** [comment]
Added 5.6.5 in the artifacts with 13ff9c7e.

Also, please check your command:
./bin/kibana-plugin install 'https://git.bitsensor.io/front-end/elastalert-kibana-plugin/builds/artifacts/kibana5/raw/artifact/elastalert-5.6.5-latest.zip?job=build'
