### ISSUE TITLE
Elastsalert kibana plugin configurations

### ISSUE THREAD

**Issue by bharathphatak** [bitsensor/elastalert-kibana-plugin#35]
Hi Team,

I have installed 5.6.2 plugin. I am not seen any new or other options.

I see the ES configuration is missing.Please can someone share plugin configurations.?

This is not a issue.#NeedInformation

Thanks

**Comment by stobias123** [comment]
I think I'm having the same issue.... Screen is blank with 5.6.2

**Comment by stobias123** [comment]
Expanding on this, looks like the api is trying to hit localhost despite setting the elastalert.serverHost variable.

**Comment by martijnrondeel** [comment]
This should be fixed in the [5.6.8 branch](https://github.com/bitsensor/elastalert-kibana-plugin/tree/5.6.8). Please try updating to that version and let us know if the issue persists.

**Comment by stobias123** [comment]
Any pointers as to what's going on here? I'd really like to be able to use kibana plugin

**Comment by willouuu** [comment]
I have same error for kibana 6.2.3

**Comment by martijnrondeel** [comment]
This issue should be fixed in the latest release available [here](https://github.com/bitsensor/elastalert-kibana-plugin/releases).
