### ISSUE TITLE
Kibana 5.6.6 Support

### ISSUE THREAD

**Issue by cadextcp** [bitsensor/elastalert-kibana-plugin#38]
Hey Guys, when can we see Kibana 5.6.6 support for this fine project?

**Comment by povils** [comment]
it is now 5.6.7 :(

**Comment by rathko** [comment]
And 5.6.8

**Comment by ichintu** [comment]
Same looking for 5.6.8 support

**Comment by martijnrondeel** [comment]
Support for the latest stable Kibana releases will be worked on this weekend. See https://github.com/bitsensor/elastalert-kibana-plugin/issues/37#issuecomment-376907423.

**Comment by martijnrondeel** [comment]
As I said support for the latest Kibana releases has been added (although 6.2.3 support remains experimental). You can find a working version of the plugin for Kibana 5.6.8 [here](https://github.com/bitsensor/elastalert-kibana-plugin/tree/5.6.8).
