### ISSUE TITLE
Error after successful install on Kibana 5.4.x

### ISSUE THREAD

**Issue by darz82** [bitsensor/elastalert-kibana-plugin#39]
Hi all,

I'm getting the below error after successfully installing the plugin on Kibana 5.4.1, any tips on how to resolve this issue.?

**Fatal Error**
**TypeError: _modules.uiModules is undefined** **(http://10.9.18.92:8081/app/kibana/bundles/elastalert.bundle.js?v=15104:29)**

**Version: 5.4.1**
**Build: 15104**

**Error: TypeError: _modules.uiModules is undefined** **(http://10.9.18.92:8081/app/kibana/bundles/elastalert.bundle.js?v=15104:29)**
**[2491]/window.onerror@http://10.9.18.92:8081/app/kibana/bundles/commons.bundle.js?****v=15104:91:16112**

**Comment by darz82** [comment]
Anyone??

**Comment by martijnrondeel** [comment]
We don't support 5.4.1 but 5.6.8 is supported [here](https://github.com/bitsensor/elastalert-kibana-plugin/tree/5.6.8).
