### ISSUE TITLE
test this plugin on kibana5.2.1,and build error

### ISSUE THREAD

**Issue by Thinkgamer** [bitsensor/elastalert-kibana-plugin#4]
http://img.blog.csdn.net/20170221180718760?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvR2FtZXJfZ3l0/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/Center

You can click on this link to see specific questions，This is the page that appears when I visit the elastalert on the left side of kibana5

**Comment by RubieV** [comment]
Could you embed the particular image, as csdn.net seems to be unreachable and to ensure availability latere?

**Comment by Thinkgamer** [comment]
![20170221180718760](https://cloud.githubusercontent.com/assets/11739994/23346734/d911838e-fcd7-11e6-9948-362af72c30af.png)
I tested on 5.2.1,after modified version number and compiled , running kibana, occur this problem

**Comment by tatdatpham** [comment]
Same error with 5.4.0
Looking for update work with kibana 5.x
