### ISSUE TITLE
" no valid url specified " in Kibana 5.5..0 

### ISSUE THREAD

**Issue by Sujeet1604** [bitsensor/elastalert-kibana-plugin#41]
I have specified the Kibana URL in kibana.config as 
elastalert.serverHost: http://url 

again and again getting the same error

**Comment by Sujeet1604** [comment]
How I resolved this .....
1. Downloaded zip the unzip and placed into plugins folder.
2. In index.js I did the below change:

//let baseUri = `http${this._options.serverSsl ? 's' : ''}://${this._options.serverHost}:${this._options.serverPort}`;
    let baseUri = `http${this._options.serverSsl ? 's' : ''}://myHost:3030`;

3. under sever/config/schema.js

//serverHost: Joi.string().hostname().default('localhost'),
    //serverPort: Joi.number().integer().default(3030),
    serverHost: 'http://myHost',
    serverPort: 3030,

**Comment by Sujeet1604** [comment]
Basically, It is not picking the values from Kibana.config

**Comment by msergiy87** [comment]
just substitute `pwd | grep -Po '(?<=kibana-)[^-]*'` with your Kibana version

./bin/kibana-plugin install https://git.bitsensor.io/front-end/elastalert-kibana-plugin/builds/artifacts/kibana5/raw/artifact/elastalert-5.6.4-latest.zip?job=build

**Comment by RubieV** [comment]
Are you willing to PR a fix and tests?
