### ISSUE TITLE
any plans for kibana 6.1.x ?

### ISSUE THREAD

**Issue by drstokes** [bitsensor/elastalert-kibana-plugin#43]

**Comment by martijnrondeel** [comment]
There is currently no support for 6.1.x, but I did add (experimental) support for 6.2.3 [here](https://github.com/bitsensor/elastalert-kibana-plugin/tree/5.6.8). I won't add a branch with 6.1.x support personally but if anyone else wants to, feel free to make a PR.

**Comment by martijnrondeel** [comment]
There's a rewritten plugin available that currently supports Kibana 6.3.1. More information is available here: https://github.com/bitsensor/elastalert-kibana-plugin/issues/56
