### ISSUE TITLE
please look it. install sense error!

### ISSUE THREAD

**Issue by amorZhu** [bitsensor/elastalert-kibana-plugin#45]
[vagrant@localhost kibana-6.2.2-linux-x86_64]$ ./bin/kibana-plugin install https://download.elasticsearch.org/elastic/sense/sense-latest.tar.gz
Attempting to transfer from https://download.elasticsearch.org/elastic/sense/sense-latest.tar.gz
Transferring 1386775 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Error: end of central directory record signature not found
    at /vagrant_data/kibana-6.2.2-linux-x86_64/node_modules/yauzl/index.js:179:14
    at /vagrant_data/kibana-6.2.2-linux-x86_64/node_modules/yauzl/index.js:539:5
    at /vagrant_data/kibana-6.2.2-linux-x86_64/node_modules/fd-slicer/index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:683:17)
Plugin installation was unsuccessful due to error "Error retrieving metadata from plugin archive"

**Comment by RubieV** [comment]
Sorry, can't help out with installing sense.

**Comment by RubieV** [comment]
Sorry, can't help out with installing sense.
