### ISSUE TITLE
Download Link broken?

### ISSUE THREAD

**Issue by samsonkolge** [bitsensor/elastalert-kibana-plugin#48]
Hi there,
I am trying to install the plugin and I am getting below error:

`#./kibana-plugin install 'https://git.bitsensor.io/front-end/elastalert-kibana-plugin/builds/artifacts/5.6.8/raw/artifact/elastalert-kibana-plugin-latest.zip?job=build'`

`Attempting to transfer from https://git.bitsensor.io/front-end/elastalert-kibana-plugin/builds/artifacts/5.6.8/raw/artifact/elastalert-kibana-plugin-latest.zip?job=build
Error: Client request error: getaddrinfo ENOTFOUND git.bitsensor.io git.bitsensor.io:443
Plugin installation was unsuccessful due to error "Client request error: getaddrinfo ENOTFOUND git.bitsensor.io git.bitsensor.io:443"`

**Comment by martijnrondeel** [comment]
Hmm we tried it on two different computers and it works here. Nonetheless, I've attached the file to this comment for you.

[elastalert-kibana-plugin-latest.zip](https://github.com/bitsensor/elastalert-kibana-plugin/files/1927953/elastalert-kibana-plugin-latest.zip)

**Comment by martijnrondeel** [comment]
If anyone else has the same issue please let us know.

**Comment by samsonkolge** [comment]
That was pretty quick. Thanks.

**Comment by samsonkolge** [comment]
Hi I am getting the below error:
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [elastalert-kibana-plugin]. Expected [5.5.0]; found [5.6.8]"

Do you have a separate file for 5.6.8? Please advise.

**Comment by martijnrondeel** [comment]
You're using Kibana 5.5.0 but trying to install the version meant for 5.6.8.

**Comment by samsonkolge** [comment]
Could you please send me the zip file for 5.6.8?

**Comment by samsonkolge** [comment]
I tried an older version (4.6.6) but it did not work:

[eng_sjc01_mon root@kibanaops02 tmp]# /usr/share/kibana/bin/kibana-plugin install file:///tmp/kibana.zip
Attempting to transfer from file:///tmp/kibana.zip
Transferring 344460 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [elastalert-kibana-plugin]. Expected [5.5.0]; found [4.6.6]"

I was not able to find any zip for 5.5.0. Do you have one or will I have to upgrade to 5.6.8?

**Comment by samsonkolge** [comment]
okay. Thanks. I will do so. Appreciate your assistance. :)
