### ISSUE TITLE
"no valid URL specified" on install

### ISSUE THREAD

**Issue by callahan22** [bitsensor/elastalert-kibana-plugin#49]
Hi,

I'm running Kibana 6.0.0. Any attempt to install this addon in either as 5.6.8 or the later 6.2.3 results in the following failure message:

```
c:\ELK\kibana\bin>kibana-plugin install 'https://git.bitsensor.io/front-end/elastalert-kibana-plugin/builds/artifacts/5.6.8/raw/artifact/elastalert-kibana-plugin-latest.zip?jo
b=build'
Attempting to transfer from 'https://git.bitsensor.io/front-end/elastalert-kibana-plugin/builds/artifacts/5.6.8/raw/artifact/elastalert-kibana-plugin-latest.zip?job=build'
Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/'https://git.bitsensor.io/front-end/elastalert-kibana-plugin/builds/artifacts/5.6.8/raw/artif
act/elastalert-kibana-plugin-latest.zip?job=build'/'https://git.bitsensor.io/front-end/elastalert-kibana-plugin/builds/artifacts/5.6.8/raw/artifact/elastalert-kibana-plugin-la
test.zip?job=build'-6.0.0.zip
Plugin installation was unsuccessful due to error "No valid url specified."
```

**Comment by AntoineBouron** [comment]
I'm getting the same error message on version 6.2.3

**Comment by martijnrondeel** [comment]
Are you able to download the file manually (just copy the link in your browser or `wget` it) or does that also malfunction? Might be something up with our pipeline.

**Comment by AntoineBouron** [comment]
So I removed the simple quote at the start and at the end of the url in the installation section.

`./bin/kibana-plugin install 'https://git.bitsensor.io/front-end/elastalert-kibana-plugin/builds/artifacts/6.2.3/raw/artifact/elastalert-kibana-plugin-latest.zip?job=build'`

should be :
`./bin/kibana-plugin install https://git.bitsensor.io/front-end/elastalert-kibana-plugin/builds/artifacts/6.2.3/raw/artifact/elastalert-kibana-plugin-latest.zip?job=build`

**Comment by martijnrondeel** [comment]
Ahh. Which platform are you on @AntoineBouron?

**Comment by martijnrondeel** [comment]
It seems on Windows the quotes break the installation but on some Linux shells they are necessary, I have changed the installation instructions in new releases to remove the quotes.
