### ISSUE TITLE
Does not work in Kibana 5.2.1

### ISSUE THREAD

**Issue by Vitiate** [bitsensor/elastalert-kibana-plugin#5]
I adjusted the kibana version in the package so that it would install into kibana. I then ran into an issue where the chrome.setTabDefaults function no longer exists, I commented this out and was able to view the top level rules page. From here nothing seemed to work at all.

**Comment by RubieV** [comment]
Let's use this issue for Kibana 5 support. Feel free to start with some commits! 

@Vitiate are you sure you are also running the Docker with RESTful API?

**Comment by Vitiate** [comment]
I manually installed and verified the RESTful API in my ELK environment. The existing rule names were displayed. Double clicking on them brought up a blank page, It appeared to be an issue with the integration to kibana. It may have been related to the removal of the tab defaults..

**Comment by callmewhy** [comment]
it seems that there are some break changes in Kibana5, and there is no document for plugins.
How do you guys develop this plugin for Kibana4? Is there any document?

**Comment by RubieV** [comment]
https://www.timroes.de/2015/12/02/writing-kibana-4-plugins-basics/ describes
most of the issues around Kibana 4 plugin development.

Op vr 10 mrt. 2017 om 08:54 schreef Haiyang Wang <notifications@github.com>:

**Comment by callmewhy** [comment]
Hey guys, I forked and fix some error for Kibana5, and tested in my computer with 5.2.2.

The fork repo url: https://github.com/baoban/elastalert-kibana-plugin, in branch kibana5

**Comment by sarbazx** [comment]
@callmewhy Hi, I have used your fork on Elasticsearch 5.2.2 with kibana and I'm getting I'm getting this error:

`Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [elastalert]. Expected [5.2.1]; found [5.2.2]"`

**Comment by RubieV** [comment]
You need to manually change the version, even the minor. grep -R '5.2.2'
and edit.

Op do 16 mrt. 2017 14:28 schreef Taskhyn Maksim <notifications@github.com>:

**Comment by RubieV** [comment]
Update for convenient installation at https://bitsensor.io/blog/community-update-alerting-in-kibana
