### ISSUE TITLE
Editor wrapper not sized properly

### ISSUE THREAD

**Issue by steve21168** [bitsensor/elastalert-kibana-plugin#50]
The plugin is working as intended functionally but when I attempt to edit a rule or create a new rule the editor window is very small and does not seem to scale based on browser window size.

Environment: kibana:6.2.3 official image on Docker
Browsers Affected: Chrome, Safari, Firefox
Plugins: xpack monitoring, searchguard 6.2.3, and this plugin via: "https://git.bitsensor.io/front-end/elastalert-kibana-plugin/builds/artifacts/6.2.3/raw/artifact/elastalert-kibana-plugin-latest.zip?job=build"

Image shown below: 
<img width="1347" alt="elastalert" src="https://user-images.githubusercontent.com/16465010/39777178-d8d47552-52d0-11e8-9ec2-84086de320b0.png">

If I manually edit the css for class .editor-wrapper and change the height in the web browser it's useable.

**Comment by martijnrondeel** [comment]
This issue is fixed in the [latest release](https://github.com/bitsensor/elastalert-kibana-plugin/releases).
