### ISSUE TITLE
Incorrect Kibana version in plugin [elastalert-kibana-plugin]. Expected [6.2.2]; found [6.2.3]

### ISSUE THREAD

**Issue by kevindwei** [bitsensor/elastalert-kibana-plugin#52]
Incorrect Kibana version in plugin [elastalert-kibana-plugin]. Expected [6.2.2]; found [6.2.3]

**Comment by kevindwei** [comment]
when i install 6.2.3elastalert-kibana-plugin，it happend this error

**Comment by kevindwei** [comment]
my kibana version is 6.2.2

**Comment by martijnrondeel** [comment]
If you are able to upgrade your Kibana installation to verson 6.3.1 you can try out the rewritten plugin which solves a lot of issues. More information here: https://github.com/bitsensor/elastalert-kibana-plugin/issues/56
