### ISSUE TITLE
Version 6.2.4 visualization

### ISSUE THREAD

**Issue by Misakiri** [bitsensor/elastalert-kibana-plugin#53]
Hi!
When we edit some alert, it appears to small and we have to scroll to see it complete

![screenshot](https://user-images.githubusercontent.com/20046498/41225616-7c9fc944-6d6f-11e8-9909-ae4e8a52d64e.png)

**Comment by martijnrondeel** [comment]
If you are running Kibana 6.3.1 please try out the rewritten version of the plugin (https://github.com/bitsensor/elastalert-kibana-plugin/issues/56) and tell us how it works!
