### ISSUE TITLE
Unable to display "Create New Rule" button, Kibana 5.6.8

### ISSUE THREAD

**Issue by fravoi** [bitsensor/elastalert-kibana-plugin#55]
Hello guys,

Using ElastAlert server with nodejs/npm, my Kibana 5.6.8 and my ElastAlert work separately but I can't display the"Create New Rule" button and obviously can't create/a a new rule using kibana interface ...
DIstribution : Centos 7

Btw, I can't use docker, there's an error when executing "make build" (sorry if my docker's problem is trivial, I've never used it ....) :
" Step 1/27 : FROM alpine:latest as py-ea
Error parsing reference: "alpine:latest as py-ea" is not a valid repository/tag: invalid reference format
make: *** [build] Error 1
"

**Comment by fravoi** [comment]
Retrieving one of my two indices makes it work (???) even if the design is pretty poor : I have the "rules overview" title, the icon to refresh rules and a tiny scroll bar right and when I scroll I indeed see the "new rule" button ; and yes it was efinitely not there before when there were two indices (with one which doesn't work because graylog used a weird timestamp). 

However, I have another problem : when I create an elastalert rule from kibana, it is created but with wrong permissions (no "x"/execution permission ...). Is there a way to change those default permissions ?

**Comment by martijnrondeel** [comment]
This issue is fixed in the [latest release](https://github.com/bitsensor/elastalert-kibana-plugin/releases).
