### ISSUE TITLE
Unsuccessful installation on ES 6.4

### ISSUE THREAD

**Issue by enemene123** [bitsensor/elastalert-kibana-plugin#58]
Hello,
I get this error notification installing the Elastalert plugin.

` installation was unsuccessful due to error "Incorrect Kibana version in plugin [elastalert-kibana-plugin]. Expected [6.4.0]; found [6.2.3]`

Is this plugin not updated anymore, or does the 6.2.3 version work with the latest release and I have to install it in another way?
Thanks for your help.

**Comment by catalinvr** [comment]
Hi @enemene123 

For Kibana 6.2.3 I saw that you can install using the following method.
`./bin/kibana-plugin install 'https://git.bitsensor.io/front-end/elastalert-kibana-plugin/builds/artifacts/6.2.3/raw/artifact/elastalert-kibana-plugin-latest.zip?job=build'`

For 6.4.x you can install from here https://github.com/bitsensor/elastalert-kibana-plugin/releases
`./kibana-plugin install  https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/1.0.0-alpha.2/elastalert-kibana-plugin-1.0.0-alpha.2-6.4.0.zip`

Best,
C

**Comment by martijnrondeel** [comment]
For Kibana version 6.3.1 and higher you can use the pre-release version from our GitHub [releases](https://github.com/bitsensor/elastalert-kibana-plugin/releases) page like @catalinvr suggested.

So far it seems the pre-release is stable enough so I will be merging the develop branch into master next week and release the new version as stable release.
