### ISSUE TITLE
install plugin error on Kibana 5.2.1 - No kibana plugins found in archive

### ISSUE THREAD

**Issue by charliezhao** [bitsensor/elastalert-kibana-plugin#6]
tom@tom-virtual-machine:~/kibana-5.2.1-linux-x86_64$ ./bin/kibana-plugin install https://git.bitsensor.io/front-end/elastalert-kibana-plugin/builds/5251/artifacts/file/build/elastalert-0.0.6.zip
Attempting to transfer from https://git.bitsensor.io/front-end/elastalert-kibana-plugin/builds/5251/artifacts/file/build/elastalert-0.0.6.zip
Transferring 8607971 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Plugin installation was unsuccessful due to error "No kibana plugins found in archive"

**Comment by gilisade** [comment]
same issue here 
kibana 5.2.0

have you managed to solve that?

**Comment by vvijayabhanu** [comment]
For Kibana 5 the plugin must be added to an empty "kibana" directory.
Inside the kibana directory create a folder in the name of plugin and then run the command 
bin\kibana-plugin install file://<path>(// in case of windows)

**Comment by gilisade** [comment]
Hi thanks for your reply !
What do you mean by empty "kibana" directory?
Did you mean i should create a directory , location irralevent , cp the plugin zip to that directory , create another directory in the "kibana" folder with the name of the plugin ? And run the command ? I tried that and got the same error...  i guess i did not understand the solution

**Comment by somaz80** [comment]
I am also having the same issue. can you please elaborate on the resolution

**Comment by somaz80** [comment]
I  am trying to execute
c:\kibana>C:\NONIBM\kibana\bin\kibana-plugin install file:///kibana/metric_vis_colors.zip
Attempting to transfer from file:///kibana/metric_vis_colors.zip
Transferring 8016 bytes....................
Transfer complete
Retrieving metadata from plugin archive
**Plugin installation was unsuccessful due to error "No kibana plugins found in archive"**

**Comment by ryan-dyer-sp** [comment]
Anyone figure out how to fix this?

**Comment by troydavis85** [comment]
I had a similar issue with a different plugin.  Kibana 5 plugins are very sensitive to the directory structure they are placed in.  Here is how I solved it.

1) Unzip plugin
2) Check package.json to make sure Kibana version matches what you have
3) Contents of zip must be placed in the following directory structure kibana/name_of_plugin/contents_of_zip
(note) The parent directory that kibana goes in doesn't matter. The name of the plugin is also located in package.json.  Make sure the directory under kibana is named exactly this.  
5) Once you have your directory structure sorted out, zip it back up. Top level should include kibana folder
6) Run the install command (kibana-plugin install file:///kibana/metric_vis_colors.zip)

**Comment by thanh3d** [comment]
thanks @troydavis85 but still got the same error :(( I have done as 5 steps above

**Comment by vvijayabhanu** [comment]
create a directory named kibana
place the contents of your plugin in a directory in the name of plugin and place this inside kibana folder
now zip the kibana folder and if you want you can name the zip as sample.zip
Now run the install command kibana-plugin install file:///kibana/sample.zip

**Comment by thanh3d** [comment]
> /usr/share/kibana/bin/kibana-plugin install file:///home/kibana/elastalert.zip 
> Attempting to transfer from file:///home/kibana/elastalert.zip
> Transferring 8903094 bytes....................
> Transfer complete
> Retrieving metadata from plugin archive
> Plugin installation was unsuccessful due to error "No kibana plugins found in archive"

**Comment by joequery** [comment]
I was having the same problem. This regex in the `analyzeArchive` function for zip files helped me figure it out.

https://github.com/elastic/kibana/blob/6ae4a07cff7569b3038551cf85fcb0a0f617e42d/src/cli_plugin/install/zip.js#L16

```
const regExp = new RegExp('(kibana[\\\\/][^\\\\/]+)[\\\\/]package\.json', 'i');
```

This means the directory structure kibana expects when installing from a local zip is

```
kibana/
    plugin-name/
        package.json
        index.js
```

**Comment by adel-s** [comment]
Install is simple:
* Download https://git.bitsensor.io/front-end/elastalert-kibana-plugin/builds/5251/artifacts/file/build/elastalert-0.0.6.zip
* Unzip
* Move unzipped elastalert dir into empty ./kibana dir
* Change "version" into package.json to your version
* Zip kibana dir. You should get this structure inside your zip file:
/kibana
-/elastalert
--/node_modules
--/public
--/server
--/index.js
--/package.json
* then install like this:
```
 cd /usr/share/kibana
 ./bin/kibana-plugin install file:///tmp/elastalert.zip

 Attempting to transfer from file:///tmp/elastalert.zip
 Transferring 8982895 bytes....................
 Transfer complete
 Retrieving metadata from plugin archive
 Extracting plugin archive
 Extraction complete
 Optimizing and caching browser bundles...
 Plugin installation complete   
```
* then restart kibana
`service kibana restart`

* if you got this error into kibana log:
 `FATAL { Error: EACCES: permission denied, open '/usr/share/kibana/optimize/bundles/graph.entry.js'`

easy fix:
`chown -R kibana:kibana /usr/share/kibana`

and restart kibana service again

After this kibana starts correctly I see elastalert in kibana menu. But got this problem when try to open it:
```Fatal Error Uncaught ReferenceError: require is not defined (https://kibana<myserver>/bundles/elastalert.bundle.js?v=14723:12)```

Does anybody knows how to fix it?

**Comment by hijakk** [comment]
I'm running into the same issue, after building from source for Kibana 5.4.1

Uncaught ReferenceError: require is not defined (http://localhost:5601/bundles/elastalert.bundle.js?v=15104:12)
Version: 5.4.1
Build: 15104
Error: Uncaught ReferenceError: require is not defined (http://localhost:5601/bundles/elastalert.bundle.js?v=15104:12)
    at window.onerror (http://localhost:5601/bundles/commons.bundle.js?v=15104:91:17805)

**Comment by mounikakuchana** [comment]
Hi

**Comment by RubieV** [comment]
@adel-s we're releasing the support up to Kibana 5.4.1 this week, a new branch, https://github.com/bitsensor/elastalert-kibana-plugin/tree/kibana5, has been created to support it. It would be great to see a commit with your explanation to the README.

**Comment by RubieV** [comment]
Update for convenient installation at https://bitsensor.io/blog/community-update-alerting-in-kibana

**Comment by rozmir** [comment]
After installing the plugin (ISM) I am getting this error: (Kibana 7.2.1)

kibana[25353]: Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`


Thanks!

**Comment by sandeepkanabar** [comment]
> I had a similar issue with a different plugin. Kibana 5 plugins are very sensitive to the directory structure they are placed in. Here is how I solved it.
> 
> 1. Unzip plugin
> 2. Check package.json to make sure Kibana version matches what you have
> 3. Contents of zip must be placed in the following directory structure kibana/name_of_plugin/contents_of_zip
>    (note) The parent directory that kibana goes in doesn't matter. The name of the plugin is also located in package.json.  Make sure the directory under kibana is named exactly this.
> 4. Once you have your directory structure sorted out, zip it back up. Top level should include kibana folder
> 5. Run the install command (kibana-plugin install file:///kibana/metric_vis_colors.zip)

Super helpful. Thanks a ton.

**Comment by Aquazee** [comment]
If anybody was trying directly from bin like this **kibana-plugin install url-here**. It still gives error. 

**Solution:**
You just need to do **./kibana-plugin install url-here**
