### ISSUE TITLE
Add Port to elastalert.serverHost Option.

### ISSUE THREAD

**Issue by Mugen1991** [bitsensor/elastalert-kibana-plugin#60]
Is it possible to add a specific port to the serverHost Parameter ? 
I tried elastalert.serverHost: testserver.testdomain:3030 and this raised an error.

**Comment by martijnrondeel** [comment]
Which version of Kibana and the ElastAlert plugin are you running?

**Comment by martijnrondeel** [comment]
If you're running the new version for Kibana 6.3.1+ please check the [configuration properties](https://github.com/bitsensor/elastalert-kibana-plugin/tree/develop#configuration) and try if those work.

**Comment by Mugen1991** [comment]
I am running kibana 6.2.4. Guess I have to upgrade.  Thanks for your quick reply :-)
