### ISSUE TITLE
Error 502 bad gateway

### ISSUE THREAD

**Issue by Ihsan8** [bitsensor/elastalert-kibana-plugin#65]
When I installed the elastalert I got the error 502 bad gateway " connect ECONNREFUCED 127.0.0.1:3030"
Please help to solve it.
I am using elk 6.4.1

**Comment by martijnrondeel** [comment]
Are you running the ElastAlert server?

**Comment by martijnrondeel** [comment]
Did you manage to solve this issue @Ihsan8 ?

**Comment by wyj1363295965** [comment]
@Ihsan8 Did you manage to solve this issue？I have encountered the same problem @martijnrondeel

**Comment by csbogdan** [comment]
Add 
elastalert-kibana-plugin.serverHost: <es_ip/host>
elastalert-kibana-plugin.serverPort: <es_port>

in your kibana.yml.
