### ISSUE TITLE
kibana 安装elastalert插件

### ISSUE THREAD

**Issue by wyj1363295965** [bitsensor/elastalert-kibana-plugin#70]
elastalert启动是3030端口么，我没有看到他的端口，在kibana.yml里应该怎么填elastalert-kibana-plugin.serverHost 和elastalert-kibana-plugin.serverPort:？

**Comment by martijnrondeel** [comment]
Could you please try to explain this issue in English?

**Comment by wyj1363295965** [comment]
@martijnrondeel Is elastalert booting 3030? I did not see his port, how should I fill elastalert-kibana-plugin.serverHost and elastalert-kibana-plugin.serverPort in kibana.yml?

**Comment by martijnrondeel** [comment]
@wyj1363295965 Are you running the [ElastAlert Docker container](https://github.com/bitsensor/elastalert)?

**Comment by wyj1363295965** [comment]
@martijnrondeel Running in this way?
docker run -d -p 3030:3030 \
    -v `pwd`/config/elastalert.yaml:/opt/elastalert/config.yaml \
    -v `pwd`/config/config.json:/opt/elastalert-server/config/config.json \
    -v `pwd`/rules:/opt/elastalert/rules \
    -v `pwd`/rule_templates:/opt/elastalert/rule_templates \
    --net="host" \
    --name elastalert bitsensor/elastalert:lates
