### ISSUE TITLE
ElastAlert Kibana Plugin error : undefined - [object Object]

### ISSUE THREAD

**Issue by Akhisar** [bitsensor/elastalert-kibana-plugin#80]
Hello,

I am getting undefined - [object Object] while selecting ElastAlert Kibana Plugin. Any insight on this..

![screen shot 2018-11-21 at 19 04 13](https://user-images.githubusercontent.com/39437317/48844797-e7026e00-edc0-11e8-8e06-2aee3ba1dd0d.png)

**Comment by duanyifei1937** [comment]
same issue

**Comment by duanyifei1937** [comment]
> same issue

had fix

**Comment by Akhisar** [comment]
My issue was I did not had the elastalert service running. I started a docker instance and the error is fixed.

**Comment by cdamir-tc** [comment]
> > same issue
> 
> had fix

Can you share your fix, please :D
