### ISSUE TITLE
6.5.1

### ISSUE THREAD

**Issue by davidkarlsen** [bitsensor/elastalert-kibana-plugin#82]
Do you have a 6.5.1 release too?

**Comment by jxycbjhc** [comment]
me too need wait online！！！

**Comment by asmoporma** [comment]
+1

**Comment by sujithpaily** [comment]
+1

**Comment by martijnrondeel** [comment]
Sorry for the delay, there is a 6.5.1 release now available [here](https://github.com/bitsensor/elastalert-kibana-plugin/releases/tag/1.0.1).
