### ISSUE TITLE
Kibana 6.5.2 support

### ISSUE THREAD

**Issue by sujithpaily** [bitsensor/elastalert-kibana-plugin#83]
Kibana 6.5.2 released. Waiting for plugin upgrade

**Comment by martijnrondeel** [comment]
[Done](https://github.com/bitsensor/elastalert-kibana-plugin/releases/tag/1.0.1).

**Comment by memelet** [comment]
Is the source now being maintained elsewhere? I don't see the actual updates to support 6.5.1.

**Comment by martijnrondeel** [comment]
@memelet No updates are needed to support 6.5.1, I just recompile the plugin for that specific Kibana version and upload it to the [releases](https://github.com/bitsensor/elastalert-kibana-plugin/releases).

**Comment by memelet** [comment]
It seems the updates to package.json for previous releases is not in git. That is what I meant about "actual updates".
