### ISSUE TITLE
port 3030 is not used.

### ISSUE THREAD

**Issue by leeypp** [bitsensor/elastalert-kibana-plugin#85]
Is elastalert booting 3030?
If I don't use docker, how to start it and port booting 3030
```
python -m elastalert.elastalert --config config.yaml --rule example_frequency.yaml --verbose
````
use this command,elastalert process is normal,but I did not see 3030 port

**Comment by martijnrondeel** [comment]
You will need to use our [ElastAlert API wrapper](https://github.com/bitsensor/elastalert) in order to have this plugin work.
