### ISSUE TITLE
Weird python errors.  Trying to query bitsensor index, but there isn't one.

### ISSUE THREAD

**Issue by eclipsecyber** [bitsensor/elastalert-kibana-plugin#88]
1) I'm curious why it's trying to query a bitsensor index rather than the elastalert_* indexes?  Is that bitsensor index supposed to exist? because it never got created when I installed the plugin.
2) I turned all the debug options on in the elastalert-config.json to make it more verbose, but it started just spitting out all the failed rules.  Are those rule "ERRORS" actual errors?  Is that normal?  Thanks for any help you can give!!

08:43:56.900Z ERROR elastalert-server:
    ProcessController:  WARNING:elasticsearch:GET http://es-user:pwd@172.17.0.1:9200/bitsensor/_search?ignore_unavailable=true&size=0 [status:400 request:0.002s]

08:43:56.900Z ERROR elastalert-server:
    ProcessController:  ERROR:root:Error running query: RequestError(400, u'parsing_exception', u'no [query] registered for [query]')

08:43:56.901Z ERROR elastalert-server:
    ProcessController:  INFO:elastalert:Skipping writing to ES: {'message': "Error running query: RequestError(400, u'parsing_exception', u'no [query] registered for [query]')", 'traceback': ['Traceback (most recent call last):', '  File "/opt/elastalert/elastalert/elastalert.py", line 544, in get_hits_aggregation', "    res = self.current_es.search(index=index, doc_type=rule.get('doc_type'), body=query, size=0, ignore_unavailable=True)", '  File "/usr/lib/python2.7/site-packages/elasticsearch-6.3.1-py2.7.egg/elasticsearch/client/utils.py", line 76, in _wrapped', '    return func(*args, params=params, **kwargs)', '  File "/usr/lib/python2.7/site-packages/elasticsearch-6.3.1-py2.7.egg/elasticsearch/client/__init__.py", line 660, in search', "    doc_type, '_search'), params=params, body=body)", '  File "/usr/lib/python2.7/site-packages/elasticsearch-6.3.1-py2.7.egg/elasticsearch/transport.py", line 318, in perform_request', '    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)', '  File "/usr/lib/python2.7/site-packages/elasticsearch-6.3.1-py2.7.egg/elasticsearch/connection/http_requests.py", line 90, in perform_request', '    self._raise_error(response.status_code, raw_data)', '  File "/usr/lib/python2.7/site-packages/elasticsearch-6.3.1-py2.7.egg/elasticsearch/connection/base.py", line 125, in _raise_error', '    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)', "RequestError: RequestError(400, u'parsing_exception', u'no [query] registered for [query]')"], 'data': {'rule': 'Attack threshold exceeded'}}

**Comment by martijnrondeel** [comment]
The only place where it uses the `bitsensor` index is in the rule_templates listed [here](https://github.com/bitsensor/elastalert/tree/master/rule_templates), so if you use those be sure to change the `index: ...` property in the rule.

As for the errors, please show the rule that you're trying to use.
