### ISSUE TITLE
Kibana 5.4.1 elastalert "require is not defined" error

### ISSUE THREAD

**Issue by hijakk** [bitsensor/elastalert-kibana-plugin#9]
I'm running into the same issue reported by others in earlier versions of Kibana, after building from source for Kibana 5.4.1

Uncaught ReferenceError: require is not defined (http://localhost:5601/bundles/elastalert.bundle.js?v=15104:12)
Version: 5.4.1
Build: 15104
Error: Uncaught ReferenceError: require is not defined (http://localhost:5601/bundles/elastalert.bundle.js?v=15104:12)
    at window.onerror (http://localhost:5601/bundles/commons.bundle.js?v=15104:91:17805)

**Comment by Passpes** [comment]
Can you fix this plugin for kibana 5.4.0?

**Comment by bopinto** [comment]
Why was this closed? Is it fixed?

**Comment by CodingSpiderFox** [comment]
See #13
