### ISSUE TITLE
Can't install plugin on kibana docker container

### ISSUE THREAD

**Issue by joshrideshark** [bitsensor/elastalert-kibana-plugin#90]
**My kibana dockerfile is as follows:**
```
ARG ELK_VERSION

# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana-oss:${ELK_VERSION}

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
RUN ./bin/kibana-plugin install https://git.bitsensor.io/front-end/elastalert-kibana-plugin/builds/artifacts/kibana5/raw/artifact/elastalert-`pwd | grep -Po '(?<=kibana-)[^-]*'`-latest.zip?job=build
```

**When doing a docker-compose build on the docker-elk stack I get the following:**
Building elasticsearch
Step 1/2 : ARG ELK_VERSION
Step 2/2 : FROM docker.elastic.co/elasticsearch/elasticsearch-oss:${ELK_VERSION}
 ---> c4f8af5c694e
Successfully built c4f8af5c694e
Successfully tagged rideshark-docker-elk-stack_elasticsearch:latest
Building logstash
Step 1/2 : ARG ELK_VERSION
Step 2/2 : FROM docker.elastic.co/logstash/logstash-oss:${ELK_VERSION}
 ---> 6db0bf56b875
Successfully built 6db0bf56b875
Successfully tagged rideshark-docker-elk-stack_logstash:latest
Building kibana
Step 1/3 : ARG ELK_VERSION
Step 2/3 : FROM docker.elastic.co/kibana/kibana-oss:${ELK_VERSION}
 ---> 91dfcdc951cc
Step 3/3 : RUN ./bin/kibana-plugin install https://git.bitsensor.io/front-end/elastalert-kibana-plugin/builds/artifacts/kibana5/raw/artifact/elastalert-`pwd | grep -Po '(?<=kibana-)[^-]*'`-latest.zip?job=build
 ---> Running in e5c1dd761424
```
Attempting to transfer from https://git.bitsensor.io/front-end/elastalert-kibana-plugin/builds/artifacts/kibana5/raw/artifact/elastalert--latest.zip?job=build
Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/https://git.bitsensor.io/front-end/elastalert-kibana-plugin/builds/artifacts/kibana5/raw/artifact/elastalert--latest.zip?job=build/https://git.bitsensor.io/front-end/elastalert-kibana-plugin/builds/artifacts/kibana5/raw/artifact/elastalert--latest.zip?job=build-6.5.4.zip
Plugin installation was unsuccessful due to error "No valid url specified."
ERROR: Service 'kibana' failed to build: The command '/bin/sh -c ./bin/kibana-plugin install https://git.bitsensor.io/front-end/elastalert-kibana-plugin/builds/artifacts/kibana5/raw/artifact/elastalert-`pwd | grep -Po '(?<=kibana-)[^-]*'`-latest.zip?job=build' returned a non-zero code: 70 
```

**I am getting a "Plugin installation was unsuccessful due to error "No valid url specified."" error. I've taken the install link directly from the elastalert docker hub page. Is this URL out of date???**

**Comment by martijnrondeel** [comment]
The instructions on Docker hub are outdated, please follow the instructions [here](https://github.com/bitsensor/elastalert-kibana-plugin#installation).

**Comment by joshrideshark** [comment]
There are no installation instructions. It literally just says download the plugin. Am I still able to add a "RUN" command in my docker file? Or should I instead be adding "COPY" command to copy in the plugin?

**Comment by martijnrondeel** [comment]
This should work for you:

```
RUN ./bin/kibana-plugin install https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/1.0.1/elastalert-kibana-plugin-1.0.1-${ELK_VERSION}.zip
```

**Comment by joshrideshark** [comment]
Yes thank you it did. It just seems that the dockerhub link was out of date.
