### ISSUE TITLE
release date for kibana version 6.6.1

### ISSUE THREAD

**Issue by smarshal-Quest** [bitsensor/elastalert-kibana-plugin#95]
Do yo have a  ETA for when 6.6.1 version will be available?

thanks

**Comment by martijnrondeel** [comment]
Just uploaded a 6.6.1 release [here](https://github.com/bitsensor/elastalert-kibana-plugin/releases/tag/1.0.2), thanks for notifying!

**Comment by smarshal-Quest** [comment]
perfect thanks
