### ISSUE TITLE
Question : Contributing to Elastalert Plugin Steps

### ISSUE THREAD

**Issue by robincher** [bitsensor/elastalert-kibana-plugin#96]
Hi there,

We are using Elastalert Plugin actively for our ELK monitoring, and appreciate that it is being open-sourced. It will be great if we can also actively contribute to this plugins, and allow it to be up-to-date with the latest Kibana LTS releases.

It wouldn't be that straight forward like editing the node package to the targeted kibana version in package.json ? Any compiling steps required? 

```
"kibana": {
    "version": "6.6.2"	  
  },	 

```
Please correct me if i missed out anything. :)

**Comment by martijnrondeel** [comment]
There's two ways to update the version yourself when there isn't a release yet:

- You can download an older build (usually minor and patch version mismatches are ok and shouldn't break anything), open the .zip and change the kibana version in `package.json` to your version.
- Or you can pull the repo and run `yarn build -k targeted-kibana-version-here`, but this requires a Kibana [development environment](https://github.com/elastic/kibana/blob/6.6/CONTRIBUTING.md#setting-up-your-development-environment) to be setup.

I try to keep up to date with new Kibana versions and upload new plugin releases asap but in case there is no release yet an issue on GitHub with the request is appreciated :+1:.

**Comment by robincher** [comment]
Hi @martijnrondeel   ,

Thanks for the help!

i take a deeper look into both options. Kinda new in developing/managing Kibana plugins,so its worth a try :)
