### ISSUE TITLE
release date for kibana version 6.7.0

### ISSUE THREAD

**Issue by aoslee** [bitsensor/elastalert-kibana-plugin#99]
Do you have a ETA for when 6.7.0 version will be available?

Thanks .

**Comment by ajaysheoran2323** [comment]
I am also looking for the same. I got the error:

Plugin installation was unsuccessful due to error "Plugin elastalert-kibana-plugin [6.6.2] is incompatible with Kibana [6.7.0]"

**Comment by martijnrondeel** [comment]
I'm testing a new release for 6.7.0 as we speak.

**Comment by martijnrondeel** [comment]
[1.0.3](https://github.com/bitsensor/elastalert-kibana-plugin/releases/tag/1.0.3) has support for Kibana 6.7+.

**Comment by aoslee** [comment]
Hi :
1.0.3 build is error.

`Attempting to transfer from https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/1.0.3/elastalert-kibana-plugin-1.0.3-6.7.0.zip`
`Transferring 22930892 bytes`
`Transfer complete`
`Retrieving metadata from plugin archive`
`Error: end of central directory record signature not found`
 `   at /usr/share/kibana/node_modules/yauzl/index.js:179:14`
`    at /usr/share/kibana/node_modules/yauzl/index.js:539:5`
`    at /usr/share/kibana/node_modules/fd-slicer/index.js:32:7`
`    at FSReqWrap.wrapper [as oncomplete] (fs.js:463:17)`
`Plugin installation was unsuccessful due to error "Error retrieving metadata from plugin archive"`
`The command '/bin/sh -c /usr/share/kibana/bin/kibana-plugin install https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/1.0.3/elastalert-kibana-plugin-1.0.3-6.7.0.zip' returned a non-zero code: 70`

Dockerfile:
`FROM  docker.elastic.co/kibana/kibana:6.7.0`
`ENV NODE_OPTIONS='--max-old-space-size=4096'`
`RUN /usr/share/kibana/bin/kibana-plugin install  https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/1.0.3/elastalert-kibana-plugin-1.0.3-6.7.0.zip`

**Comment by Akhisar** [comment]
Can you please add support for 6.7.2 also.

**Comment by tntxyz** [comment]
How can I build plugin from source code for new kibana release, Is there any documents?
